DROP TABLE IF EXISTS bookmarks;

CREATE TABLE bookmarks (
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
title text NOT NULL,
url text NOT NULL,
rating integer,
description text
);

INSERT INTO bookmarks (title, url, rating, description)
VALUES
('google', 'https://google.com', '5', 'search engine'),
('google', 'https://google.com', '5', 'search engine'),
('google', 'https://google.com', '5', 'search engine');